# 开发环境特定配置
# 例如，覆盖数据库连接信息、Redis 连接信息、日志级别等

# spring:
#   datasource:
#     url: jdbc:mysql://dev-db-host:3306/admin_dev?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
#     username: dev_user
#     password: dev_password
#   data:
#     redis:
#       host: dev-redis-host
#       port: 6379

# logging:
#   level:
#     com.spark.adminserver: debug 