# 测试环境特定配置
# 例如，覆盖数据库连接信息、Redis 连接信息、日志级别等

# spring:
#   datasource:
#     url: jdbc:mysql://test-db-host:3306/admin_test?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
#     username: test_user
#     password: test_password
#   data:
#     redis:
#       host: test-redis-host
#       port: 6379

# logging:
#   level:
#     com.spark.adminserver: info 